# basic options
title: Your awesome title
author: Github user
email: myemail@email.com
description: A wonderful site
twitter_username: jekyllrb
github_username: soccerjoe

#Build settings
markdown: kramdown
theme: minima
